import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:fynnedge/core/money/money.dart';
import 'package:fynnedge/data/engine/financial_engine.dart';

/// Proves the Flutter engine agrees with the Laravel engine, case for case.
///
/// The fixture is generated by the backend
/// (`php artisan fynn:parity-fixture`), which is authoritative. If either
/// engine changes a definition or a rounding rule, this test fails — which is
/// the point: a customer must never see one number in a live estimate and a
/// different one after saving.
void main() {
  const engine = FinancialEngine();

  final file = File('test/fixtures/financial_parity.json');
  if (!file.existsSync()) {
    // Failing loudly rather than skipping: parity is not optional, and a
    // missing fixture means the setup is broken.
    test('the parity fixture is present', () {
      fail(
        'test/fixtures/financial_parity.json is missing. Regenerate it with:\n'
        '  cd ../fynnedge-api && php artisan fynn:parity-fixture',
      );
    });
    return;
  }

  final fixture = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final asOf = DateTime.parse(fixture['as_of'] as String);
  final cases = (fixture['cases'] as List).cast<Map<String, dynamic>>();

  test('the fixture covers the whole agreed matrix', () {
    expect(cases, hasLength(greaterThanOrEqualTo(10)));
    final names = cases.map((c) => c['name'] as String).toList();
    // The cases the module brief calls for, by name.
    expect(names, contains('case_1_normal'));
    expect(names, contains('case_2_zero_income'));
    expect(names, contains('case_3_zero_emi'));
    expect(names, contains('case_4_no_other_obligations'));
    expect(names, contains('case_5_high_obligations'));
    expect(names, contains('case_6_no_goals'));
    expect(names, contains('case_7_multiple_goals'));
    expect(names, contains('case_8_goal_completed'));
    expect(names, contains('case_9_deadlines'));
    expect(names, contains('case_10_large_and_precise'));
  });

  for (final testCase in cases) {
    final name = testCase['name'] as String;
    final input = testCase['input'] as Map<String, dynamic>;
    final expected = testCase['expected'] as Map<String, dynamic>;

    group(name, () {
      final profile = (input['profile'] as Map).cast<String, dynamic>();

      final snapshot = engine.snapshot(
        income: Money.of(profile['monthly_income']),
        expenses: Money.of(profile['monthly_expenses']),
        existingEmi: Money.of(profile['existing_emi']),
        otherObligations: Money.of(profile['other_obligations']),
        savings: Money.of(profile['savings']),
      );

      test('profile figures match the backend', () {
        final e = (expected['derived'] as Map).cast<String, dynamic>();

        expect(snapshot.surplus.rupees, _num(e['surplus']), reason: 'surplus');
        expect(
          snapshot.totalOutgo.rupees,
          _num(e['monthly_outgo']),
          reason: 'monthly_outgo',
        );
        expect(
          snapshot.emiRatio.value,
          _num(e['emi_ratio']),
          reason: 'emi_ratio',
        );
        expect(
          snapshot.expenseRatio.value,
          _num(e['expense_ratio']),
          reason: 'expense_ratio',
        );
        expect(
          snapshot.outgoRatio.value,
          _num(e['outgo_ratio']),
          reason: 'outgo_ratio',
        );
        expect(
          snapshot.emergencyMonths.value,
          _num(e['emergency_months']),
          reason: 'emergency_months',
        );
        expect(snapshot.hasIncome, e['has_income'], reason: 'has_income');
      });

      test('inputs survive parsing exactly', () {
        final e = (expected['inputs'] as Map).cast<String, dynamic>();
        expect(snapshot.income.rupees, _num(e['monthly_income']));
        expect(snapshot.expenses.rupees, _num(e['monthly_expenses']));
        expect(snapshot.existingEmi.rupees, _num(e['existing_emi']));
        expect(snapshot.otherObligations.rupees, _num(e['other_obligations']));
        expect(snapshot.savings.rupees, _num(e['savings']));
      });

      final goalInputs = (input['goals'] as List).cast<Map<String, dynamic>>();
      final expectedGoals = (expected['goals'] as Map).cast<String, dynamic>();
      final expectedItems = (expectedGoals['items'] as List)
          .cast<Map<String, dynamic>>();

      if (goalInputs.isEmpty) {
        test('no goals still yields valid totals', () {
          expect(expectedItems, isEmpty);
          expect(_num(expectedGoals['total_target']), 0);
          expect(_num(expectedGoals['total_monthly_required']), 0);
        });
      }

      for (var i = 0; i < goalInputs.length; i++) {
        final g = goalInputs[i];
        final want = expectedItems[i];

        test('goal "${g['title']}" matches the backend', () {
          final metrics = engine.goalMetrics(
            target: Money.of(g['target_amount']),
            saved: Money.of(g['saved_amount']),
            targetDate: asOf.add(Duration(days: g['days_from_as_of'] as int)),
            asOf: asOf,
          );

          expect(
            metrics.remaining.rupees,
            _num(want['remaining_amount']),
            reason: 'remaining',
          );
          expect(metrics.progress, _num(want['progress']), reason: 'progress');
          expect(
            metrics.monthsRemaining,
            want['months_remaining'],
            reason: 'months_remaining',
          );
          expect(
            metrics.monthlyRequired.rupees,
            _num(want['monthly_required']),
            reason: 'monthly_required',
          );
          expect(
            metrics.isComplete,
            want['is_complete'],
            reason: 'is_complete',
          );
          expect(metrics.isOverdue, want['is_overdue'], reason: 'is_overdue');
        });
      }

      if (goalInputs.isNotEmpty) {
        test('aggregate goal figures match the backend', () {
          var target = Money.zero;
          var saved = Money.zero;
          var remaining = Money.zero;
          var monthly = Money.zero;

          for (final g in goalInputs) {
            final metrics = engine.goalMetrics(
              target: Money.of(g['target_amount']),
              saved: Money.of(g['saved_amount']),
              targetDate: asOf.add(Duration(days: g['days_from_as_of'] as int)),
              asOf: asOf,
            );
            target = target + metrics.target;
            saved = saved + metrics.saved;
            remaining = remaining + metrics.remaining;
            monthly = monthly + metrics.monthlyRequired;
          }

          expect(target.rupees, _num(expectedGoals['total_target']));
          expect(saved.rupees, _num(expectedGoals['total_saved']));
          expect(remaining.rupees, _num(expectedGoals['total_remaining']));
          expect(
            monthly.rupees,
            _num(expectedGoals['total_monthly_required']),
            reason: 'total_monthly_required',
          );
        });
      }
    });
  }
}

/// The fixture holds whole values as ints and the rest as doubles; compare on
/// a single numeric type.
double _num(Object? value) => (value as num).toDouble();
